// >>> kj:managed:commitlint v1 >>> (do not edit: regenerated by kj harden)
// Conventional Commits — header <=100 chars, lowercase subject.
export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "header-max-length": [2, "always", 100],
    "subject-case": [2, "never", ["sentence-case", "start-case", "pascal-case", "upper-case"]],
  },
};
// <<< kj:managed:commitlint <<<
