// >>> kj:managed:eslint v1 >>> (do not edit: regenerated by kj harden)
export default [
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    languageOptions: { ecmaVersion: 2025, sourceType: "module" },
    rules: {
      "no-var": "error",
      "no-eval": "error",
      "no-new-func": "error",
      "no-restricted-globals": [
        "error",
        { name: "alert", message: "Use the app modal, not alert()." },
        { name: "confirm", message: "Use the app modal, not confirm()." },
        { name: "prompt", message: "Use the app modal, not prompt()." },
        { name: "escape", message: "Use encodeURIComponent()." },
        { name: "unescape", message: "Use decodeURIComponent()." },
        { name: "event", message: "Use the handler parameter, not window.event." },
      ],
      "no-restricted-properties": [
        "error",
        { object: "document", property: "write", message: "Use DOM nodes / Blob URLs, not document.write." },
        { object: "document", property: "writeln", message: "Use DOM nodes, not document.writeln." },
        { property: "substr", message: "Use slice() or substring(), not substr()." },
      ],
    },
  },
];
// <<< kj:managed:eslint <<<
