sonar.projectKey=presentation-camera
sonar.projectName=presentation-camera
sonar.sources=.
sonar.exclusions=vendor/**,node_modules/**,.firebase/**,poc/**,docs/**
sonar.tests=.
sonar.test.inclusions=**/*.test.js
